server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh
#          uri: http://localhost:8001
          uri: lb://CLOUD-PROVIDER-SERVICE #服务名配置  lb://代表loadbalance
          predicates: Path=/payment/get/**

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PROVIDER-SERVICE
          predicates:
            - Path=/**
            - After=2020-08-22T16:42:32.731+08:00[Asia/Shanghai]
#            - Cookie=username,cjy  #不生效，原因没查
#            - Header=X-Request-Id, \d+  #请求头带正则, 哦欧无效

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    hostname: cloud-gateway-service